# Generated by Django 5.0.14 on 2026-06-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('aadhaar_pvc', 'Aadhaar PVC'), ('pan_pvc', 'PAN PVC'), ('voter_pvc', 'Voter PVC'), ('apaar', 'APAAR Card'), ('ayushman', 'Ayushman Bharat'), ('school_id', 'School ID'), ('employee_id', 'Employee ID'), ('visitor_id', 'Visitor ID'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('front_bg_color', models.CharField(default='#1a237e', max_length=7)),
                ('back_bg_color', models.CharField(default='#283593', max_length=7)),
                ('accent_color', models.CharField(default='#ffca28', max_length=7)),
                ('has_qr', models.BooleanField(default=False)),
                ('has_barcode', models.BooleanField(default=False)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='id_card_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDCardGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=120)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='id_cards/generated/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='id_cards/generated/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='id_cards/pdfs/')),
                ('cost_charged', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='id_cards.idcardtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
