# Generated by Django 5.2.13 on 2026-06-21 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_cards', '0002_farmeridcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50)),
                ('fare_shop_number', models.CharField(blank=True, max_length=50)),
                ('scheme_name', models.CharField(blank=True, max_length=50)),
                ('head_of_family', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('issue_date', models.CharField(blank=True, max_length=20)),
                ('photo', models.TextField(blank=True)),
                ('family_members', models.JSONField(blank=True, default=list)),
                ('print_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ration_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
