# Generated by Django 5.2.13 on 2026-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_cards', '0003_rationcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcard',
            name='design_style',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
