# Generated by Django 5.0.14 on 2026-06-23 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id_width', models.FloatField(default=3.22)),
                ('farmer_id_height', models.FloatField(default=2.15)),
                ('ration_card_width', models.FloatField(default=3.71)),
                ('ration_card_height', models.FloatField(default=2.34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
