# Generated by Django 5.0.14 on 2026-06-21
from django.db import migrations

def add_farmer_id_service(apps, schema_editor):
    Service = apps.get_model('pricing', 'Service')
    # Use update_or_create to avoid duplicates
    Service.objects.update_or_create(
        slug='farmer-id',
        defaults={
            'name': 'Farmer ID Card Print',
            'price': 50.00,
            'is_active': True,
            'icon': 'bi-card-heading',
            'description': 'Real-time generation and printing of Farmer ID cards.'
        }
    )

def remove_farmer_id_service(apps, schema_editor):
    Service = apps.get_model('pricing', 'Service')
    Service.objects.filter(slug='farmer-id').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_farmer_id_service, reverse_code=remove_farmer_id_service),
    ]
