# Generated by Django 5.0.14 on 2026-06-21
from django.db import migrations

def add_ration_card_service(apps, schema_editor):
    Service = apps.get_model('pricing', 'Service')
    # Use update_or_create to avoid duplicates
    Service.objects.update_or_create(
        slug='ration-card',
        defaults={
            'name': 'Ration Card Print',
            'price': 50.00,
            'is_active': True,
            'icon': 'bi-card-list',
            'description': 'Real-time generation and printing of Smart Ration Cards.'
        }
    )

def remove_ration_card_service(apps, schema_editor):
    Service = apps.get_model('pricing', 'Service')
    Service.objects.filter(slug='ration-card').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_add_farmer_id_service'),
    ]

    operations = [
        migrations.RunPython(add_ration_card_service, reverse_code=remove_ration_card_service),
    ]
