# Generated by Django 5.2.13 on 2026-06-26 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('id_cards', '0004_rationcard_design_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='farmer_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_record', to='id_cards.farmeridcard'),
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='ration_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_record', to='id_cards.rationcard'),
        ),
    ]
