# Generated by Django 5.2.13 on 2026-06-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_customertransaction_farmer_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertransaction',
            name='customer',
        ),
    ]
