# Generated by Django 5.0.14 on 2026-06-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity'), ('education', 'Education'), ('land', 'Land Records'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=20)),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter', 'Voter ID'), ('passport', 'Passport'), ('dl', "Driver's Licence"), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
